### PR TITLE
Support multiple log path

### PR DESCRIPTION
**Pull request by edwin--zhao**
Avoid a service is repeatedly reload

### CODE REVIEW

**Comment by egarbi** [comment]
this is related to #13

**Comment by edwin--zhao** [comment]
@egarbi 
yes, I met the same question #13 , I am such a solution, and then submit the merge request.

**Comment by egarbi** [comment]
@edwin--zhao thanks for that, your code worked perfectly for me. I don't know why this wasn't merged yet

**Comment by aboe76** [comment]
@edwin--zhao could you update the pillar.example with this, so it's documented...
then I think this can be merged.

**Comment by aboe76** [comment]
thanks

**Pull request merged**
