### PR TITLE
Added support for FreeBSD

### PR DESCRIPTION
**Pull request by msiebeneicher**
hi,

i added the basic support for FreeBSD. Worked fine in general (tested on FreeBSD 10.2) - The necessary cronjob will not added to the crontab automatically - that is correct, right?

### CODE REVIEW

**Comment by aboe76** [comment]
@msiebeneicher I don't know how freebsd packaged logrotate, if they automatically include a cronjob 

If I look for logrotate and freebsd I get something about newsyslog.conf?
see: http://www.claudiokuenzler.com/blog/474/looking-for-logrotate-in-freebsd-newsyslog.conf

**Comment by msiebeneicher** [comment]
@aboe76 : newsyslog is the default BSD program to handle log file rotation which is preinstalled on BSD based systems. So normally you don't need logrotate for basic log rotation: https://www.freebsd.org/cgi/man.cgi?query=newsyslog&sektion=8&apropos=0&manpath=FreeBSD+10.2-RELEASE

Did the debian installation automatically add the logrotate cronjob or do you also have to add it after the installation manually?

**Comment by aboe76** [comment]
@msiebeneicher debian automatically installs a cron.d entry for logrotate.
so that's why it isn't in the formula, besides not all Os-es use cron for logrotate, some use systemd-timers...

**Comment by msiebeneicher** [comment]
@aboe76: alright - i will check the automatic cron addition again and add a state in case that no cron will added automatically.

**Comment by javierbertoli** [comment]
@msiebeneicher, @aboe76 closing this as #35 was merged and added support for FreeBSD. Thanks you both!

**Pull request closed without merging**
