### PR TITLE
Allow managing logrotate defaults

### PR DESCRIPTION
**Pull request by EvaSDK**
I wanted to get away from `nodateext` rotations on my Debian installations but the current formula would not allow me changing that without forking it so I decided to share the hopefully generic enough patches to handle that.

I am not fully satisfied by some key names use in the pillar but had to deal with existing configurations.

### CODE REVIEW

**Comment by aboe76** [comment]
Hi @EvaSDK I will test this first

**Comment by aboe76** [comment]
something about the pillar.example and the logrotate.conf, doesn't work.
it's not a list but a dict...

**Comment by EvaSDK** [comment]
This should be good now.

**Comment by javierbertoli** [comment]
Thanks!

**Pull request merged**
