### PR TITLE
add Scientific Linux support

### PR DESCRIPTION
**Pull request by kmkramer**
We would to add support for Scientific Linux. Please review. Thanks

### CODE REVIEW

**Comment by aboe76** [comment]
thanks

**Comment by kmkramer** [comment]
interesting, I thought that would be enough but oddly on SL file management doesn't appear to be working. it won't update /etc/logrotate.conf or update/create any jobs in /etc/logrotate.d/

**Comment by kmkramer** [comment]
and the minion shows the correct job info
```
local:
    ----------
    logrotate:
        ----------
        jobs:
            ----------
            syslog:
                ----------
                config:
                    - sharedscripts
                    - postrotate
                    - /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
                    - endscript
                path:
                    - /var/log/cron
                    - /var/log/maillog
                    - /var/log/messages
                    - /var/log/secure
                    - /var/log/spooler
                    - /var/log/slapd.log
        lookup:
            ----------
            pkg:
                logrotate
            service:
                crond
```

**Comment by aboe76** [comment]
@kmkramer could you please edit your comment with "```" code blocks, otherwise I can't see the indentations.

**Comment by aboe76** [comment]
@kmkramer could you show me the states you have added to the minion?
are they logrotate, logrotate.config and logrotate.jobs ?
or only logrotate.

**Comment by kmkramer** [comment]
- logrotate

Only

**Comment by aboe76** [comment]
Then that's the reason, the config state manages the conf file. The jobs
state the jobs,

Op do 9 feb. 2017 22:56 schreef Kevin Kramer <notifications@github.com>:

**Comment by kmkramer** [comment]
duh! sorry about that.

salt-call state.apply logrotate.config is working now
salt-call state.apply logrotate.jobs is not

```
local:
    - Rendering SLS 'base:logrotate.jobs' failed: Jinja syntax error: no test named 'mapping'; line 20

      ---
      [...]
          - group: {{ salt['pillar.get']('logrotate:config:group', logrotate.group) }}
          - mode: {{ salt['pillar.get']('logrotate:config:mode', '644') }}
          - require:
            - pkg: logrotate
          - context:
            {% if value is mapping %}    <======================
            path: {{ value.get('path', []) }}
            data: {{ value.get('config', []) }}
            {% else %}
            path: {{ key }}
            data: {{ value }}
      [...]
      ---
```

**Comment by aboe76** [comment]
@kmkramer to old version of salt that's the reason for the mapping error.

**Pull request merged**
